[target.msp430-none-elf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-mcpu=msp430",
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-lmul_none",
    "-C", "link-arg=-lgcc",
]

[build]
target = "msp430-none-elf"

[unstable]
build-std = ["core"]
